### ISSUE TITLE
[Request for assist]ERROR when benchmarking inplace NTT

### ISSUE THREAD

**Issue by sss1h** [ingonyama-zk/icicle#291] opened 2023-12-06 13:01 UTC
I meet an error when I use `benches/ntt.rs` to benchmark `inplace NTT`.
`AnalyzingCriterion.rs ERROR: At least one measurement of benchmark NTT/Scalar inplace NTT of size 2^20 in batch 1 took zero time per iteration. This should not be possible. If using iter_custom, please verify that your routine is correctly measured.
`
Detail as below
![image](https://github.com/ingonyama-zk/icicle/assets/49825610/6c7cdeb0-73bf-4610-a216-11ee14341760)

My cmake version is 3.28.0-rc5.
cuda version is Cuda compilation tools, release 12.1, V12.1.66.

**Comment by vhnatyk** [comment] 2023-12-06 13:55
caused by #211 - should be fixed soon

**Comment by vhnatyk** [comment] 2024-01-08 21:27
fixed in v1.0.0

**Closed by vhnatyk** 2024-01-08 21:27 UTC
Labels: backlog
