### ISSUE TITLE
[BUG]: Rust won't compile

### ISSUE THREAD

**Issue by vaqxai** [ingonyama-zk/icicle#582] opened 2024-08-20 13:18 UTC
## Description

When trying to compile a Rust library depending on icicle, I get a linking error:
```
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH=
```
(a very long string of paths and arguments)
```
  = note: rust-lld: error: relocation R_X86_64_PC32 cannot be used against symbol 'typeinfo for std::invalid_argument'; recompile with -fPIC
          >>> defined in /usr/lib/gcc/x86_64-linux-gnu/10/libstdc++.so
          >>> referenced by tmpxft_00003335_00000000-6_poseidon.cudafe1.cpp
          >>>               poseidon.cu.o:(partial_rounds_number_from_arity(unsigned int)) in archive /usr/local/cargo/git/checkouts/icicle-9b25725c9b5d6dd2/bd72fb7/target/release/build/libingo_icicle.a
          
          rust-lld: error: relocation R_X86_64_PC32 cannot be used against symbol 'std::cerr'; recompile with -fPIC
          >>> defined in /usr/lib/gcc/x86_64-linux-gnu/10/libstdc++.so
          >>> referenced by tmpxft_00002e57_00000000-6_msm.cudafe1.cpp
          >>>               msm.cu.o:(checkLast(char const*, int)) in archive /usr/local/cargo/git/checkouts/icicle-9b25725c9b5d6dd2/bd72fb7/target/release/build/libingo_icicle.a
```
followed by more of the "relocation cannot be used against symbol"

full output: https://pastebin.com/VZZxSEY3
  

### Reproduce

compile ezkl with --features=icicle

## Expected Behavior

the compilation goes through

## Environment

Please complete the following information:

OS + Version: linux debian 11

Cargo Version: 1.81.0-nightly (2024-07-16)

GPU type: Nvidia H100 SXM

## Additional context

Please provide any additional context that may be helpful in confirming and resolving this issue.

**Comment by emirsoyturk** [comment] 2024-08-20 13:41
To resolve this issue, please try using the following branch of the ICICLE: [ezkl-icicle2](https://github.com/ingonyama-zk/icicle/tree/ezkl-icicle2). This branch contains the fix for linking error you're experiencing.

**Comment by vaqxai** [comment] 2024-08-21 08:38
That branch does not contain any rust package files, and thus can't be used as a cargo dependency

**Comment by emirsoyturk** [comment] 2024-08-21 09:00
Could you please specify the versions of icicle and ezkl you're using? I can't reproduce the error you encountered. I am able to clone ezkl directly and build it using the command `cargo build --release --features icicle` without any issues.

**Comment by vaqxai** [comment] 2024-08-21 09:26
Also when just merging the branch with the rust branch manually:
`2024-08-21T09:23:36.295256763Z   gmake: *** No rule to make target 'icicle'.  Stop.`

I was trying to use this in my local `Cargo.toml`
```
[patch.'https://github.com/ingonyama-zk/icicle']
icicle = { git = "https://github.com/ingonyama-zk/icicle", branch="ezkl-icicle2" }
```
which resulted with `no package "icicle" found in repository`, which is expected, as that branch doesn't contain a `Cargo.toml`.

I'm using my own ezkl which was cloned from the ezkl main branch, with minor modifications, none of which concern icicle.

I'm building my own crate with a feature, `gpu` which is resolved as this:
```
[features]
gpu = [
    "ezkl-lib/icicle"
]

**Comment by emirsoyturk** [comment] 2024-08-21 09:46
Can you clone the ezkl repo and try running the command `cargo build --release --features icicle`? As I mentioned before, I cannot reproduce the error when I built the new cloned the EZKL repository.

**Comment by vaqxai** [comment] 2024-08-21 12:05
EZKL is using a different branch of icicle than the one you specified. Which one should I use? The one EZKL wants does not work (with the error I sent at the top)

**Comment by emirsoyturk** [comment] 2024-08-22 06:42
You should use the branch that EZKL is already using. As I mentioned, I couldn't reproduce the error you described. However, could you make sure EZKL is using [this](https://github.com/ingonyama-zk/icicle/tree/fix/vhnat/ezkl-build-fix) branch. It contains the necessary linking fix for older version of ICICLE.

**Comment by vaqxai** [comment] 2024-08-22 07:12
Yeah it's the correct branch, this is the error i'm getting now:
Maybe i'm using a bad version of CUDA Toolkit? Is 12.6 alright?
```
  19 errors detected in the compilation of "/home/vaqxai/.cargo/git/checkouts/icicle-9b25725c9b5d6dd2/bd72fb7/icicle/curves/bls12_381/poseidon.cu".
  gmake[3]: *** [CMakeFiles/icicle.dir/build.make:244: CMakeFiles/icicle.dir/curves/bls12_381/poseidon.cu.o] Error 2
  gmake[3]: *** Waiting for unfinished jobs....
  gmake[2]: *** [CMakeFiles/Makefile2:83: CMakeFiles/icicle.dir/all] Error 2
  gmake[1]: *** [CMakeFiles/Makefile2:90: CMakeFiles/icicle.dir/rule] Error 2
  gmake: *** [Makefile:124: icicle] Error 2
  thread 'main' panicked at /home/vaqxai/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.51/src/lib.rs:1100:5:

  command did not execute successfully, got: exit status: 2

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by emirsoyturk** [comment] 2024-08-22 11:29
You might need to clone the halo2 repository and update the ICICLE version there and you need to use local halo2 in EZKL ofc. Alternatively, you can override the ICICLE version in the EZKL toml file.

Since the problem is resolved, I'm closing the issue.

**Closed by emirsoyturk** 2024-08-22 11:29 UTC
Labels: type:bug
