### ISSUE TITLE
[BUG]: Error while compiling on Google colab T4 instance

### ISSUE THREAD

**Issue by aniketpr01** [ingonyama-zk/icicle#301] opened 2023-12-14 15:40 UTC
## Description

While setting up the repo on Google colab notebook, had issue compiling the repo,

### Reproduce

Steps listed as:
https://github.com/gkigiermo/rust-cuda-colab/blob/main/rust_icicle_cuda.ipynb

Command:
!ls -la
%cd icicle/icicle
!mkdir -p build
!cmake -S . -B build
!time cmake --build build

Error Output
total 140
drwx------ 5 root root   4096 Dec 14 15:21 appUtils
drwx------ 3 root root   4096 Dec 14 15:21 build
-rw------- 1 root root   6033 Dec 14 15:21 CMakeLists.txt
drwx------ 2 root root   4096 Dec 14 15:21 curves
-rw------- 1 root root 112820 Dec 14 15:21 Doxyfile
drwx------ 2 root root   4096 Dec 14 15:21 primitives
-rw------- 1 root root   3329 Dec 14 15:21 README.md
drwx------ 2 root root   4096 Dec 14 15:21 utils
[Errno 2] No such file or directory: 'icicle/icicle'
/content/drive/MyDrive/workspace/icicle/icicle
CMake Error at CMakeLists.txt:77 (message):
  The value of CURVE variable: is not one of the supported curves:
  bn254;bls12_381;bls12_377;bw6_761

-- Configuring incomplete, errors occurred!
gmake: Makefile: No such file or directory
gmake: *** No rule to make target 'Makefile'.  Stop.

real	0m0.050s
user	0m0.034s
sys	0m0.014s

## Expected Behavior

Should pass compiling the repo in the T4 instance

## Environment

T4  instance Google Colab
!nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

Versions

!rustc --version
rustc 1.70.0 (90c541806 2023-05-31) (built from a source tarball)

!cargo --version
cargo 1.70.0

!nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

!gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

!cmake --version
cmake version 3.27.9
CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by ImmanuelSegol** [comment] 2023-12-14 15:43
I'll try to reproduce this just to make sure it's not broken.

**Comment by ImmanuelSegol** [comment] 2023-12-14 18:24
Hey @aniketpr01

So the issue is with this:

<img width="382" alt="image" src="https://github.com/ingonyama-zk/icicle/assets/11227560/001812b2-2d73-4a73-b484-52c65cd3546c">


We updated our makefile to compile one curve each run. The correct command would be:

cmake -S . -B build -DCURVE=bn254

fixed it here https://github.com/gkigiermo/rust-cuda-colab/pull/1

**Comment by aniketpr01** [comment] 2023-12-15 04:15
Awesome, Thanks @ImmanuelSegol

**Comment by ImmanuelSegol** [comment] 2023-12-15 04:17
@aniketpr01 perfect! I'm closing the issue. If any other issues arise feel free to open a new ticket.

**Closed** 2023-12-15 04:17 UTC
Labels: type:bug
