### ISSUE TITLE
[TEST]: test test_bls12_377::tests_bls12_377::test_point_evaluation broken

### ISSUE THREAD

**Issue by ImmanuelSegol** [ingonyama-zk/icicle#239] opened 2023-10-03 12:22 UTC
## Description

test `test_bls12_377::tests_bls12_377::test_point_evaluation broken` is broken.

```
running 75 tests
test curves::bls12_377::tests::test_ark_scalar_convert ... ok
test curves::bls12_377::tests::test_point_equality ... ok
test curves::bls12_381::tests::test_ark_scalar_convert ... ok
test curves::bls12_381::tests::test_point_equality ... ok
test curves::bn254::tests::test_ark_scalar_convert ... ok
test curves::bn254::tests::test_point_equality ... ok
test test_bls12_377::tests_bls12_377::test_batch_commit ... ok
test test_bls12_377::tests_bls12_377::test_batch_msm ... ok
test test_bls12_377::tests_bls12_377::test_commit ... ok
test test_bls12_377::tests_bls12_377::test_msm ... ok
test test_bls12_377::tests_bls12_377::test_ntt ... ok
test test_bls12_377::tests_bls12_377::test_ntt_batch ... ok
test test_bls12_377::tests_bls12_377::test_point_batch_evaluation ... ok
test test_bls12_377::tests_bls12_377::test_point_batch_evaluation_on_coset ... ignored
test test_bls12_377::tests_bls12_377::test_point_batch_interpolation ... ok
error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `/home/administrator/actions-runner/icicle/_work/icicle/icicle/target/release/deps/icicle-989d94fe51d08[874](https://github.com/ingonyama-zk/icicle/actions/runs/6391693254/job/17347482541?pr=235#step:3:875) --test-threads=1` (signal: 11, SIGSEGV: invalid memory reference)
test test_bls12_377::tests_bls12_377::test_point_evaluation ... 
Error: Process completed with exit code 101.
```

here is an example of it failing https://github.com/ingonyama-zk/icicle/actions/runs/6391693254/job/17347482541?pr=235

**Comment by jeremyfelder** [comment] 2023-10-03 12:23
@ImmanuelSegol Is this a duplicate of #219?

**Comment by DmytroTym** [comment] 2023-11-02 14:53
Closed by https://github.com/ingonyama-zk/icicle/pull/188

**Closed by DmytroTym** 2023-11-02 14:53 UTC
Labels: area:tests, area:ci
