### ISSUE TITLE
[FEAT] Implement correct better CUDA error handling

### ISSUE THREAD

**Issue by ImmanuelSegol** [ingonyama-zk/icicle#190] opened 2023-09-18 13:51 UTC
We dont handle many of the CUDA errors correctly.

Reference: https://leimao.github.io/blog/Proper-CUDA-Error-Checking/

**Comment by jeremyfelder** [comment] 2023-09-19 07:01
@ImmanuelSegol I think this might be a duplicate of #109. Lets combine them?

**Closed** 2024-03-03 12:57 UTC
Labels: backlog
